project_id = "xqvapaavywmqswtccfqu"

[functions.create-order]
verify_jwt = true

[functions.verify-flutterwave]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false

[functions.password-login]
verify_jwt = false

[functions.submit-dealer-verification]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = true

[functions.admin-user-details]
verify_jwt = true

[functions.admin-list-dealer-verifications]
verify_jwt = true

[functions.admin-review-dealer-verification]
verify_jwt = true

[functions.admin-list-orders]
verify_jwt = true

[functions.admin-update-order-status]
verify_jwt = true
