import React, { useState } from 'react';
// @ts-ignore
import { useAdmin, UserProfile } from '../../context/AdminContext';

const TeamManagement: React.FC = () => {
    // @ts-ignore
    const { installers, addInstaller, deleteInstaller } = useAdmin();
    const [isModalOpen, setIsModalOpen] = useState(false);

    // Form State
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [phone, setPhone] = useState('');

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        const newInstaller: any = {
            fullName: name,
            email,
            phone,
            // other fields mocked or generated by addInstaller logic
        };
        await addInstaller(newInstaller);
        setIsModalOpen(false);
        setName('');
        setEmail('');
        setPhone('');
    };

    return (
        <div className="space-y-6 animate-in fade-in">
            <div className="flex items-center justify-between">
                <h2 className="text-2xl font-bold">Team Management</h2>
                <button
                    onClick={() => setIsModalOpen(true)}
                    className="px-4 py-2 bg-primary text-forest font-bold rounded-lg hover:brightness-105 flex items-center gap-2"
                >
                    <span className="material-symbols-outlined">add</span>
                    Add Installer
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {(installers || []).map((installer: UserProfile) => (
                    <div key={installer.id} className="bg-white dark:bg-[#152a17] p-6 rounded-xl border border-[#cfe7d1] dark:border-[#2a3d2c] flex flex-col gap-4">
                        <div className="flex items-center gap-4">
                            <div className="size-12 rounded-full bg-primary/20 flex items-center justify-center text-primary font-bold text-xl">
                                {installer.firstName?.[0] || 'I'}
                            </div>
                            <div>
                                <h3 className="font-bold text-lg">{installer.fullName}</h3>
                                <p className="text-sm text-gray-500">{installer.email}</p>
                            </div>
                        </div>
                        <div className="pt-4 border-t border-[#cfe7d1] dark:border-[#2a3d2c] flex justify-between items-center">
                            <span className="text-xs font-bold uppercase bg-green-100 text-green-700 px-2 py-1 rounded">Active</span>
                            <button
                                onClick={() => deleteInstaller(installer.id)}
                                className="text-red-500 hover:bg-red-50 p-2 rounded-full transition-colors"
                            >
                                <span className="material-symbols-outlined">delete</span>
                            </button>
                        </div>
                    </div>
                ))}

                {(!installers || installers.length === 0) && (
                    <div className="col-span-full py-12 text-center text-gray-500 border-2 border-dashed border-gray-200 dark:border-white/10 rounded-xl">
                        No installers added yet.
                    </div>
                )}
            </div>

            {/* Add Installer Modal */}
            {isModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setIsModalOpen(false)}></div>
                    <div className="relative bg-white dark:bg-[#152a17] rounded-2xl shadow-2xl w-full max-w-md animate-in zoom-in-95">
                        <form onSubmit={handleSubmit} className="p-6 space-y-4">
                            <h3 className="text-xl font-bold mb-4">Add New Installer</h3>

                            <div>
                                <label className="block text-xs font-bold mb-1">Full Name</label>
                                <input required value={name} onChange={e => setName(e.target.value)} className="w-full p-3 rounded-lg border border-gray-200 dark:border-white/10 bg-background-light dark:bg-black/20" />
                            </div>

                            <div>
                                <label className="block text-xs font-bold mb-1">Email</label>
                                <input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="w-full p-3 rounded-lg border border-gray-200 dark:border-white/10 bg-background-light dark:bg-black/20" />
                            </div>

                            <div>
                                <label className="block text-xs font-bold mb-1">Phone</label>
                                <input value={phone} onChange={e => setPhone(e.target.value)} className="w-full p-3 rounded-lg border border-gray-200 dark:border-white/10 bg-background-light dark:bg-black/20" />
                            </div>

                            <button type="submit" className="w-full py-3 bg-primary text-forest font-bold rounded-lg hover:brightness-105 mt-4">
                                Create Profile
                            </button>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default TeamManagement;
